var menuList = [
    {
        "children": [],
        "describe": " ",
        "icon": "fa fa-credit-card",
        "id": "dashboard",
        "level": 0,
        "menuId": "dashboard",
        "name": "首页",
        "parentId": "hsweb-pay",
        "path": "AOzA-eAC1",
        "permissionId": "",
        "sortIndex": 101,
        "url": "pages/dashboard/list"
    },
    {
        "children": [],
        "describe": " ",
        "icon": "fa fa-credit-card",
        "id": "order",
        "level": 0,
        "menuId": "order",
        "name": "交易管理",
        "parentId": "hsweb-pay",
        "path": "AOzB-eAC2",
        "permissionId": "",
        "sortIndex": 102,
        "url": "pages/order/list"
    },
    {
        "children": [
            {
                "children": [],
                "describe": " ",
                "icon": "fa fa-credit-card",
                "id": "trans",
                "level": 0,
                "menuId": "trans",
                "name": "资金记录",
                "parentId": "hsweb-pay",
                "path": "AOzB-1AC2",
                "permissionId": "",
                "sortIndex": 102,
                "url": "pages/trans/list"
            },{
                "children": [],
                "describe": " ",
                "icon": "fa fa-credit-card",
                "id": "substitute",
                "level": 0,
                "menuId": "substitute",
                "name": "代付清单",
                "parentId": "hsweb-pay",
                "path": "AOzB-yAC2",
                "permissionId": "",
                "sortIndex": 102,
                "url": "pages/substitute/list"
            }, {
                "children": [],
                "describe": " ",
                "icon": "fa fa-credit-card",
                "id": "charge",
                "level": 0,
                "menuId": "charge",
                "name": "我的费率",
                "parentId": "hsweb-pay",
                "path": "AOzB-eAC3",
                "permissionId": "",
                "sortIndex": 103,
                "url": "pages/charge/list"
            }, {
                "children": [],
                "describe": " ",
                "icon": "fa fa-credit-card",
                "id": "withdraw",
                "level": 0,
                "menuId": "withdraw",
                "name": "提现管理",
                "parentId": "hsweb-pay",
                "path": "AOzB-eAC4",
                "permissionId": "",
                "sortIndex": 104,
                "url": "pages/withdraw/list"
            }],
        "describe": " ",
        "icon": "fa fa-credit-card",
        "id": "balance",
        "level": 0,
        "menuId": "balance",
        "name": "资金管理",
        "parentId": "hsweb-pay",
        "path": "AOzB-1AC2",
        "permissionId": "",
        "sortIndex": 102,
        "url": "pages/trans/list"
    },
    {
        "children": [
            {
                "children": [],
                "describe": " ",
                "icon": "fa fa-credit-card",
                "id": "contact",
                "level": 0,
                "menuId": "contact",
                "name": "基本信息",
                "parentId": "hsweb-pay",
                "path": "AOzB-eAC3",
                "permissionId": "",
                "sortIndex": 101,
                "url": "pages/person-info/contact/list"
            },
            {
                "children": [],
                "describe": " ",
                "icon": "fa fa-credit-card",
                "id": "base",
                "level": 0,
                "menuId": "base",
                "name": "备案信息",
                "parentId": "hsweb-pay",
                "path": "AOzB-eAC1",
                "permissionId": "",
                "sortIndex": 101,
                "url": "pages/person-info/base/list"
            },
            {
                "children": [],
                "describe": " ",
                "icon": "fa fa-credit-card",
                "id": "settle",
                "level": 0,
                "menuId": "settle",
                "name": "提现信息",
                "parentId": "hsweb-pay",
                "path": "AOzB-eAC2",
                "permissionId": "",
                "sortIndex": 101,
                "url": "pages/person-info/settle/list"
            }

        ],
        "describe": " ",
        "icon": "fa fa-credit-card",
        "id": "person",
        "level": 0,
        "menuId": "person",
        "name": "个人中心",
        "parentId": "hsweb-pay",
        "path": "AOzB-eAC5",
        "permissionId": "",
        "sortIndex": 101,
        "url": "pages/base-info/list"
    },
    {
        "children": [],
        "describe": " ",
        "icon": "fa fa-credit-card",
        "id": "api",
        "level": 0,
        "menuId": "api",
        "name": "API帮助",
        "parentId": "hsweb-pay",
        "path": "AOzB-eAC5",
        "permissionId": "",
        "sortIndex": 105,
        "url": "pages/api/list"
    }];

var personMenu = [
    {
        "children": [
            {
                "children": [],
                "describe": " ",
                "icon": "fa fa-credit-card",
                "id": "base",
                "level": 0,
                "menuId": "base",
                "name": "备案信息",
                "parentId": "hsweb-pay",
                "path": "AOzB-eAC1",
                "permissionId": "",
                "sortIndex": 101,
                "url": "pages/person-info/base/list"
            },
            {
                "children": [],
                "describe": " ",
                "icon": "fa fa-credit-card",
                "id": "settle",
                "level": 0,
                "menuId": "settle",
                "name": "提现信息",
                "parentId": "hsweb-pay",
                "path": "AOzB-eAC2",
                "permissionId": "",
                "sortIndex": 101,
                "url": "pages/person-info/settle/list"
            },
            {
                "children": [],
                "describe": " ",
                "icon": "fa fa-credit-card",
                "id": "contact",
                "level": 0,
                "menuId": "contact",
                "name": "基本信息",
                "parentId": "hsweb-pay",
                "path": "AOzB-eAC3",
                "permissionId": "",
                "sortIndex": 101,
                "url": "pages/person-info/contact/list"
            },
        ],
        "describe": " ",
        "icon": "fa fa-credit-card",
        "id": "person",
        "level": 0,
        "menuId": "person",
        "name": "个人中心",
        "parentId": "hsweb-pay",
        "path": "AOzB-eAC5",
        "permissionId": "",
        "sortIndex": 101,
        "url": "pages/base-info/list"
    }];


var agentMenu = [
    {
        "children": [],
        "describe": " ",
        "icon": "fa fa-credit-card",
        "id": "dashboard",
        "level": 0,
        "menuId": "dashboard",
        "name": "首页",
        "parentId": "hsweb-pay",
        "path": "AOzA-eAC1",
        "permissionId": "",
        "sortIndex": 101,
        "url": "pages/agent/dashboard/list"
    },
    {
        "children": [],
        "describe": " ",
        "icon": "fa fa-credit-card",
        "id": "agent-order",
        "level": 0,
        "menuId": "agent-order",
        "name": "交易管理",
        "parentId": "hsweb-pay",
        "path": "AOzB-eAC6",
        "permissionId": "",
        "sortIndex": 105,
        "url": "pages/agent/order/list"
    },
    {
        "children": [],
        "describe": " ",
        "icon": "fa fa-credit-card",
        "id": "agent-trans",
        "level": 0,
        "menuId": "agent-trans",
        "name": "资金记录",
        "parentId": "hsweb-pay",
        "path": "AOzB-1AC2",
        "permissionId": "",
        "sortIndex": 102,
        "url": "pages/agent/trans/list"
    },
    {
        "children": [],
        "describe": " ",
        "icon": "fa fa-credit-card",
        "id": "charge",
        "level": 0,
        "menuId": "charge",
        "name": "我的费率",
        "parentId": "hsweb-pay",
        "path": "AOzB-eAC3",
        "permissionId": "",
        "sortIndex": 103,
        "url": "pages/charge/list"
    },
    {
        "children": [],
        "describe": " ",
        "icon": "fa fa-credit-card",
        "id": "agent-subordinate",
        "level": 0,
        "menuId": "agent-subordinate",
        "name": "下级代理",
        "parentId": "hsweb-pay",
        "path": "AOzB-eAC6",
        "permissionId": "",
        "sortIndex": 105,
        "url": "pages/agent/subordinate/list"
    },
    {
        "children": [],
        "describe": " ",
        "icon": "fa fa-credit-card",
        "id": "agent-merchant",
        "level": 0,
        "menuId": "agent-merchant",
        "name": "商户信息",
        "parentId": "hsweb-pay",
        "path": "AOzB-eAC6",
        "permissionId": "",
        "sortIndex": 105,
        "url": "pages/agent/merchant/list"
    },
    {
        "children": [],
        "describe": " ",
        "icon": "fa fa-credit-card",
        "id": "agent-withdraw",
        "level": 0,
        "menuId": "agent-withdraw",
        "name": "提现管理",
        "parentId": "hsweb-pay",
        "path": "AOzB-eAC4",
        "permissionId": "",
        "sortIndex": 104,
        "url": "pages/agent/withdraw/list"
    },
    {
        "children": [
            {
                "children": [],
                "describe": " ",
                "icon": "fa fa-credit-card",
                "id": "settle",
                "level": 0,
                "menuId": "settle",
                "name": "提现信息",
                "parentId": "hsweb-pay",
                "path": "AOzB-eAC2",
                "permissionId": "",
                "sortIndex": 101,
                "url": "pages/person-info/settle/list"
            },
            {
                "children": [],
                "describe": " ",
                "icon": "fa fa-credit-card",
                "id": "payee",
                "level": 0,
                "menuId": "payee",
                "name": "收款信息",
                "parentId": "hsweb-pay",
                "path": "AOzB-eAC2",
                "permissionId": "",
                "sortIndex": 101,
                "url": "pages/person-info/payee/list"
            }
        ],
        "describe": " ",
        "icon": "fa fa-credit-card",
        "id": "person",
        "level": 0,
        "menuId": "person",
        "name": "个人中心",
        "parentId": "hsweb-pay",
        "path": "AOzB-eAC5",
        "permissionId": "",
        "sortIndex": 101,
        "url": "pages/base-info/list"
    }];